name: Send Email on New Issue

on:
  issues:
    types: [opened]

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send SMTP Email
        uses: pconteo/send-mail-on-issue-creation@main
        with:
          smtp-host: smtp.gmail.com
          smtp-port: 465
          smtp-user: ${{ secrets.SMTP_USER }}
          smtp-pass: ${{ secrets.SMTP_PASS }}
          to-email: pierangelo.conteo@exprivia.com
          subject: 'Nuova Issue Aperta'
          body: 'Ãˆ stata aperta una nuova issue nel repository!'

